### PR TITLE
add word interop dll

### PR DESCRIPTION
**Pull request by twofingerrightclick**
## Description
Add netstandard2.0 word.interop dll to Word module. The psd1 file also was formatted in the process of saving it after adding the dll as an assembly dependency

### CODE REVIEW

**Comment by twofingerrightclick** [comment]
Do I need to update the version manually in the psd1?

**Comment by MarkMichaelis** [comment]
Yes... I believe so.

**Comment by MarkMichaelis** [comment]
@twofingerrightclick: Can you verify this will work with PowerShell Core (pwsh.exe), please?

**Comment by MarkMichaelis** [comment]
@twofingerrightclick: In addition, we should deploy to PowerShell Gallery and verify it works, please.

**Pull request merged**
